repos:
  # Batch of helpful formatters and patterns
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: check-json
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: debug-statements

  # Keep setup.cfg clean
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.5.0
    hooks:
      - id: setup-cfg-fmt

  # Format code. No, I don't like everything black does either.
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black

  # Format docs.
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black>=21.12b0]

  # Flake8 for linting, line-length adjusted to match Black default
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-builtins]
